version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2
    steps:
      - checkout
      - run:
          name: Setup Code Climate test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: bundle install
      - run:
          name: Run unit tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rake test:unit
            EXIT_CODE=${?}
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code ${EXIT_CODE}
          environment:
            COVERAGE: 'true'

workflows:
  version: 2
  pipeline:
    jobs:
      - build
